# Pandas

In [1]:
import pandas as pd
from IPython.display import HTML, Markdown, Latex


def display_df(tp_df=None, index=False):
    tp_df = tp_df if isinstance(tp_df,pd.DataFrame) else df
    display(Markdown(tp_df.to_markdown(index=index)))

# def display_df(tp_df=None, index=False):
#     tp_df = tp_df if isinstance(tp_df,pd.DataFrame) else df
#     display(HTML(tp_df.to_html(index=index)))

<br>

Converting the datatype of the values of a dataframe

In [2]:
df = pd.DataFrame({
    'A': ['2','7'],
    'B': ['6','3']
})
print(df.dtypes)

print('\n')

df = df.astype('int64')
print(df.dtypes)

A    object
B    object
dtype: object


A    int64
B    int64
dtype: object


<br>

Transpose of a matrix/dataframe

<br>

Getting the number of NaN values in each column of a dataframe

In [3]:
df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML240EN-SkillsNetwork/labs/data/Ames_Housing_Sales.csv')

dict_nans = {"Column": [], "NaN": []}
for column, nans in zip(df.columns, df.isna().sum()):
    dict_nans["Column"].append(column)
    dict_nans["NaN"].append(nans)

df = pd.DataFrame(dict_nans)
display_df()

| Column        |   NaN |
|:--------------|------:|
| 1stFlrSF      |     0 |
| 2ndFlrSF      |     0 |
| 3SsnPorch     |     0 |
| Alley         |  1297 |
| BedroomAbvGr  |     0 |
| BldgType      |     0 |
| BsmtCond      |   426 |
| BsmtExposure  |   426 |
| BsmtFinSF1    |     0 |
| BsmtFinSF2    |     0 |
| BsmtFinType1  |   426 |
| BsmtFinType2  |   427 |
| BsmtFullBath  |     0 |
| BsmtHalfBath  |     0 |
| BsmtQual      |   426 |
| BsmtUnfSF     |     0 |
| CentralAir    |     0 |
| Condition1    |     0 |
| Condition2    |     0 |
| Electrical    |     0 |
| EnclosedPorch |     0 |
| ExterCond     |     0 |
| ExterQual     |     0 |
| Exterior1st   |     0 |
| Exterior2nd   |     0 |
| Fence         |  1114 |
| FireplaceQu   |   618 |
| Fireplaces    |     0 |
| Foundation    |     0 |
| FullBath      |     0 |
| Functional    |     0 |
| GarageArea    |     0 |
| GarageCars    |     0 |
| GarageCond    |     0 |
| GarageFinish  |     0 |
| GarageQual    |     0 |
| GarageType    |     0 |
| GarageYrBlt   |     0 |
| GrLivArea     |     0 |
| HalfBath      |     0 |
| Heating       |     0 |
| HeatingQC     |     0 |
| HouseStyle    |     0 |
| KitchenAbvGr  |     0 |
| KitchenQual   |     0 |
| LandContour   |     0 |
| LandSlope     |     0 |
| LotArea       |     0 |
| LotConfig     |     0 |
| LotFrontage   |     0 |
| LotShape      |     0 |
| LowQualFinSF  |     0 |
| MSSubClass    |     0 |
| MSZoning      |     0 |
| MasVnrArea    |     0 |
| MasVnrType    |   797 |
| MiscFeature   |  1328 |
| MiscVal       |     0 |
| MoSold        |     0 |
| Neighborhood  |     0 |
| OpenPorchSF   |     0 |
| OverallCond   |     0 |
| OverallQual   |     0 |
| PavedDrive    |     0 |
| PoolArea      |     0 |
| PoolQC        |  1372 |
| RoofMatl      |     0 |
| RoofStyle     |     0 |
| SaleCondition |     0 |
| SaleType      |     0 |
| ScreenPorch   |     0 |
| Street        |     0 |
| TotRmsAbvGrd  |     0 |
| TotalBsmtSF   |     0 |
| Utilities     |     0 |
| WoodDeckSF    |     0 |
| YearBuilt     |     0 |
| YearRemodAdd  |     0 |
| YrSold        |     0 |
| SalePrice     |     0 |

<br>

Getting information like the minimum value, max value, count, mean, etc

In [4]:
df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML240EN-SkillsNetwork/labs/data/Ames_Housing_Sales.csv')
display_df(df.describe().T)

|   count |           mean |          std |   min |    25% |    50% |      75% |        max |
|--------:|---------------:|-------------:|------:|-------:|-------:|---------:|-----------:|
|    1379 |   1177.13      |   387.015    |   438 |    894 |   1098 |   1414   |   4692     |
|    1379 |    353.425     |   439.553    |     0 |      0 |      0 |    738.5 |   2065     |
|    1379 |      3.60986   |    30.1547   |     0 |      0 |      0 |      0   |    508     |
|    1379 |      2.86512   |     0.783961 |     0 |      2 |      3 |      3   |      6     |
|    1379 |    455.579     |   459.691    |     0 |      0 |    400 |    732   |   5644     |
|    1379 |     48.1022    |   164.325    |     0 |      0 |      0 |      0   |   1474     |
|    1379 |      0.430747  |     0.514052 |     0 |      0 |      0 |      1   |      2     |
|    1379 |      0.0587382 |     0.238285 |     0 |      0 |      0 |      0   |      2     |
|    1379 |    570.765     |   443.678    |     0 |    228 |    476 |    811   |   2336     |
|    1379 |     21.0392    |    60.5351   |     0 |      0 |      0 |      0   |    552     |
|    1379 |      0.641769  |     0.645985 |     0 |      0 |      1 |      1   |      3     |
|    1379 |      1.58013   |     0.548051 |     0 |      1 |      2 |      2   |      3     |
|    1379 |    500.762     |   185.681    |   160 |    380 |    484 |    580   |   1418     |
|    1379 |      1.87092   |     0.630055 |     1 |      1 |      2 |      2   |      4     |
|    1379 |   1978.51      |    24.6897   |  1900 |   1961 |   1980 |   2002   |   2010     |
|    1379 |   1534.69      |   519.141    |   438 |   1154 |   1479 |   1790   |   5642     |
|    1379 |      0.395939  |     0.502402 |     0 |      0 |      0 |      1   |      2     |
|    1379 |      1.03843   |     0.196048 |     1 |      1 |      1 |      1   |      3     |
|    1379 |  10695.8       | 10214.7      |  1300 |   7741 |   9591 |  11708.5 | 215245     |
|    1379 |     75.1123    |    28.2142   |    21 |     60 |     71 |     88   |    405.783 |
|    1379 |      4.13488   |    40.1305   |     0 |      0 |      0 |      0   |    572     |
|    1379 |     56.0225    |    41.0269   |    20 |     20 |     50 |     70   |    190     |
|    1379 |    108.365     |   184.195    |     0 |      0 |      0 |    170.5 |   1600     |
|    1379 |     42.8891    |   501.614    |     0 |      0 |      0 |      0   |  15500     |
|    1379 |      6.3343    |     2.69667  |     1 |      5 |      6 |      8   |     12     |
|    1379 |     47.2763    |    65.2105   |     0 |      0 |     27 |     69.5 |    547     |
|    1379 |      5.57796   |     1.08103  |     2 |      5 |      5 |      6   |      9     |
|    1379 |      6.18709   |     1.34578  |     2 |      5 |      6 |      7   |     10     |
|    1379 |      2.92096   |    41.3355   |     0 |      0 |      0 |      0   |    738     |
|    1379 |     15.9456    |    57.2496   |     0 |      0 |      0 |      0   |    480     |
|    1379 |      6.55257   |     1.58982  |     3 |      5 |      6 |      7   |     12     |
|    1379 |   1074.45      |   436.372    |     0 |    810 |   1008 |   1314   |   6110     |
|    1379 |     97.4569    |   126.699    |     0 |      0 |      0 |    171   |    857     |
|    1379 |   1972.96      |    29.3799   |  1880 |   1955 |   1976 |   2001   |   2010     |
|    1379 |   1985.44      |    20.4449   |  1950 |   1968 |   1994 |   2004   |   2010     |
|    1379 |   2007.81      |     1.33022  |  2006 |   2007 |   2008 |   2009   |   2010     |
|    1379 | 185480         | 79023.9      | 35311 | 134000 | 167500 | 217750   | 755000     |

<br>

Creating/modifying a column based on operations done on other columns (or itself)

In [5]:
# Creating our base dataframe
df = pd.DataFrame({
    'A': [2,7],
    'B': [6,3]
})
display_df()

# Creating a new col based on operations on other existing columns
df['C'] = df['A'] + df['B']
display_df()

# Editing that col based on the value of itself
df['C'] = df['C'] / 2
display_df()

|   A |   B |
|----:|----:|
|   2 |   6 |
|   7 |   3 |

|   A |   B |   C |
|----:|----:|----:|
|   2 |   6 |   8 |
|   7 |   3 |  10 |

|   A |   B |   C |
|----:|----:|----:|
|   2 |   6 |   4 |
|   7 |   3 |   5 |

<br>

Combining two dataframes vertically

In [6]:
df1 = pd.DataFrame({
    'A': [2,4],
    'B': [1,3]
})

df2 = pd.DataFrame({
    'B': [5,7],
    'A': [6,8]
})

combined_df = pd.concat([df1, df2])

display_df(df1)
display_df(df2)
display_df(combined_df)

|   A |   B |
|----:|----:|
|   2 |   1 |
|   4 |   3 |

|   B |   A |
|----:|----:|
|   5 |   6 |
|   7 |   8 |

|   A |   B |
|----:|----:|
|   2 |   1 |
|   4 |   3 |
|   6 |   5 |
|   8 |   7 |

<br>

Combining two dataframes horizantally

In [7]:
df1 = pd.DataFrame({
    'A': [2,7],
    'B': [6,3]
})

df2 = pd.DataFrame()
df2['C'] = df1['A'] + df1['B']

combined_df = pd.concat([df1, df2], axis=1)

display_df(df1)
display_df(df2)
display_df(combined_df)

|   A |   B |
|----:|----:|
|   2 |   6 |
|   7 |   3 |

|   C |
|----:|
|   8 |
|  10 |

|   A |   B |   C |
|----:|----:|----:|
|   2 |   6 |   8 |
|   7 |   3 |  10 |

<br>

A way to convert a 2D matrix to a dataframe where the first row is column name

In [8]:
df = pd.DataFrame([
    ['A','B'],
    [3,4],
    [9,7]
])
display_df()

df.columns = df.iloc[0]
df = df[1:]

display_df()

| 0   | 1   |
|:----|:----|
| A   | B   |
| 3   | 4   |
| 9   | 7   |

|   A |   B |
|----:|----:|
|   3 |   4 |
|   9 |   7 |

<br>

Replacing items in dataframes

In [9]:
df = pd.DataFrame({
    'A': ['A1', '?' , 'A3'],
    'B': ['?' , 'B2', 'B3']
})
display_df()

df.replace(['?'], pd.NA, inplace=True)
df # Cannot do display_df() because of an error when converting to MD, ie "boolean value of NA is ambiguous"

| A   | B   |
|:----|:----|
| A1  | ?   |
| ?   | B2  |
| A3  | B3  |

A     B
0    A1  <NA>
1  <NA>    B2
2    A3    B3

<br>

Dropping rows containing NA (or any specified value)

In [10]:
df = pd.DataFrame({
    'A': ['A1' , pd.NA, 'A3'],
    'B': [pd.NA, 'B2' , 'B3']
})
display(df)

df.dropna(inplace=True)
display(df) # Here as we can see, the index number of the row is preserved. To solve that, we can use reset_index method

# df.reset_index?
df.reset_index(inplace=True, drop=True) # drop is by default set to False. So by default, it inserts a new column called "Index"
display(df)

A     B
0    A1  <NA>
1  <NA>    B2
2    A3    B3

A   B
2  A3  B3

A   B
0  A3  B3

In [11]:
'''
round(df.describe(),2)

df.decsribe(include='object') # This will only describe the columns with object (ie string) datatype
df.describe().T

df_uniques = df.nunique()

binary_cols   = df_uniques[df_uniques == 2].index.tolist()
category_cols = df_uniques[(df_uniques > 2) & (df_uniques <= 10)].index.tolist()

correlations = df[ATTRS].corrwith(df['SalePrice'])
correlations.sort_values(inplace=True)

df.dtypes
df.T
df.value_counts(normalize=True).sort_index()
'''

"\nround(df.describe(),2)\n\ndf.decsribe(include='object') # This will only describe the columns with object (ie string) datatype\ndf.describe().T\n\ndf_uniques = df.nunique()\n\nbinary_cols   = df_uniques[df_uniques == 2].index.tolist()\ncategory_cols = df_uniques[(df_uniques > 2) & (df_uniques <= 10)].index.tolist()\n\ncorrelations = df[ATTRS].corrwith(df['SalePrice'])\ncorrelations.sort_values(inplace=True)\n\ndf.dtypes\ndf.T\ndf.value_counts(normalize=True).sort_index()\n"

<br><br><br><br><br>

# Numpy

In [12]:
import numpy as np

start   = 1
end     = 100
n_elems = 100

print(np.linspace(start, end, n_elems))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]


In [13]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [14]:
# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# Display the first row
print(arr[0])
print(arr[0, :])
# Display the first element of the first row
print(arr[0][0])
print(arr[0, 0])
# Display the first column of all rows
print(arr[:, 0])

[[1 2 3]
 [4 5 6]]
[1 2 3]
[1 2 3]
1
1
[1 4]


<br><br><br><br><br>

<br><br><br><br><br>

<br><br><br><br><br>